// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SagaPoc.FluxoCaixa.Infrastructure.Persistencia;

#nullable disable

namespace SagaPoc.FluxoCaixa.Infrastructure.Migrations.Consolidado
{
    [DbContext(typeof(ConsolidadoDbContext))]
    [Migration("20260117134233_CriarTabelaConsolidado")]
    partial class CriarTabelaConsolidado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SagaPoc.FluxoCaixa.Domain.Agregados.ConsolidadoDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comerciante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuantidadeCreditos")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeDebitos")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalCreditos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebitos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Data", "Comerciante")
                        .IsUnique()
                        .HasDatabaseName("IX_Consolidado_Data_Comerciante");

                    b.ToTable("ConsolidadosDiarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
