// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SagaPoc.Orquestrador.Persistence;

#nullable disable

namespace SagaPoc.Orquestrador.Migrations
{
    [DbContext(typeof(SagaDbContext))]
    [Migration("20260109025941_AdicionarPersistenciaSaga")]
    partial class AdicionarPersistenciaSaga
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SagaPoc.Orquestrador.Sagas.PedidoSagaData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("ID único da instância da SAGA");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("ID do cliente que fez o pedido");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Data e hora de conclusão da SAGA");

                    b.Property<DateTime?>("DataConclusaoCompensacao")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Timestamp de conclusão da compensação");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Data e hora de início do processamento da SAGA");

                    b.Property<DateTime?>("DataInicioCompensacao")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Timestamp de início da compensação");

                    b.Property<bool>("EmCompensacao")
                        .HasColumnType("boolean")
                        .HasComment("Indica se o pedido está em processo de compensação");

                    b.Property<string>("EnderecoEntrega")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Endereço para entrega do pedido");

                    b.Property<bool>("EntregadorAlocado")
                        .HasColumnType("boolean")
                        .HasComment("Indica se o entregador foi alocado");

                    b.Property<string>("EntregadorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("ID do entregador alocado (necessário para liberação)");

                    b.Property<string>("ErrosCompensacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Erros ocorridos durante a compensação");

                    b.Property<string>("EstadoAtual")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Estado atual da SAGA");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Forma de pagamento utilizada");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Mensagem de erro em caso de falha");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Motivo da rejeição/cancelamento do pedido");

                    b.Property<bool>("PagamentoProcessado")
                        .HasColumnType("boolean")
                        .HasComment("Indica se o pagamento foi processado");

                    b.Property<string>("PassosCompensados")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Lista de passos compensados com sucesso");

                    b.Property<Guid?>("PedidoRestauranteId")
                        .HasColumnType("uuid")
                        .HasComment("ID do pedido no sistema do restaurante");

                    b.Property<string>("RestauranteId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("ID do restaurante onde o pedido foi feito");

                    b.Property<bool>("RestauranteValidado")
                        .HasColumnType("boolean")
                        .HasComment("Indica se a validação do restaurante foi executada");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasComment("Número de revisão para controle de concorrência otimista");

                    b.Property<decimal>("TaxaEntrega")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Taxa de entrega cobrada");

                    b.Property<int>("TempoEntregaMinutos")
                        .HasColumnType("integer")
                        .HasComment("Tempo estimado de entrega em minutos");

                    b.Property<int>("TempoPreparoMinutos")
                        .HasColumnType("integer")
                        .HasComment("Tempo estimado de preparo do pedido em minutos");

                    b.Property<int>("TentativasCompensacao")
                        .HasColumnType("integer")
                        .HasComment("Contador de tentativas de compensação");

                    b.Property<string>("TransacaoId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("ID da transação de pagamento (necessário para estorno)");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Valor total do pedido");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_PedidoSagas_ClienteId");

                    b.HasIndex("DataInicio")
                        .HasDatabaseName("IX_PedidoSagas_DataInicio");

                    b.HasIndex("EstadoAtual")
                        .HasDatabaseName("IX_PedidoSagas_EstadoAtual");

                    b.HasIndex("RestauranteId")
                        .HasDatabaseName("IX_PedidoSagas_RestauranteId");

                    b.ToTable("PedidoSagas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
